### PR TITLE
FEAT: Attraction Orders

### PR DESCRIPTION
**Pull request by MyBackHurtsAlot**
老師好，黃柏瑄第五週作業請查收～

http://18.139.142.46:3000
http://18.139.142.46:3000/attraction/1
http://18.139.142.46:3000/booking

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Text in date input is repeating, just use default one here.
18 139 142 46_3000_attraction_1

**Comment by MyBackHurtsAlot** [comment]
Date input style has been changed into default, please take another check.


http://18.139.142.46:3000
http://18.139.142.46:3000/attraction/1
http://18.139.142.46:3000/booking

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Comment by MyBackHurtsAlot** [comment]
老師好，黃柏瑄的第六週作業請查收～

http://18.139.142.46:3000

**Review by cwpeng — APPROVED** [review]
OK. Done. Merge approved pull request before you do next task.

**Pull request merged**
