### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by MyBackHurtsAlot**
老師好我是黃柏瑄第一週作業請查收感謝

http://18.139.142.46:3000/api/attractions?page=1
http://18.139.142.46:3000/api/attractions?page=0&keyword=藝文館所
http://18.139.142.46:3000/api/attractions?page=0&keyword=北
http://18.139.142.46:3000/api/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Result is OK. But too much redundant SQL queries.

1. You should check if keyword exists first, and decide what SQL query should be executed to fetch results.
2. Don't use `SELECT id FROM attractions` to find last page, it's a very expensive query.

Try to solve these issues and re-request review.

**Comment by MyBackHurtsAlot** [comment]
Issues solved please check

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your code will execute following query even if we don't need to do keyword search.
```
    k_sql = "select * from attractions where category = %s or name like %s limit %s, %s"
    k_val = (keyword, "%" + keyword + "%", page * 12, 12,)
    cursor.execute(k_sql, k_val)
    keyword_result = cursor.fetchall()
```

**Comment by MyBackHurtsAlot** [comment]
query search improved please take another check

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by MyBackHurtsAlot** [comment]
Thanks for reviewing!

**Pull request merged**
